"""Add name and description to sessions

Revision ID: 0ce629caf52d
Revises: 4a4901b52e0a
Create Date: 2025-12-30 00:54:58.556351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ce629caf52d'
down_revision: Union[str, Sequence[str], None] = '4a4901b52e0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 添加可空列（SQLite 限制）
    op.add_column('sessions', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('sessions', sa.Column('description', sa.Text(), nullable=True))

    # 为现有数据设置默认名称
    op.execute("""
        UPDATE sessions
        SET name = '项目 ' || substr(id, 1, 8)
        WHERE name IS NULL
    """)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'description')
    op.drop_column('sessions', 'name')
    # ### end Alembic commands ###
