"""Initial schema for SQLite

Revision ID: 4a4901b52e0a
Revises: 
Create Date: 2025-12-30 00:06:09.574170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a4901b52e0a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('parent_version_id', sa.String(length=36), nullable=True),
    sa.Column('user_input', sa.Text(), nullable=True),
    sa.Column('user_feedback', sa.Text(), nullable=True),
    sa.Column('schema', sa.JSON(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('diff', sa.JSON(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_version_id'], ['versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_created_at', 'versions', ['created_at'], unique=False)
    op.create_index('idx_parent_version', 'versions', ['parent_version_id'], unique=False)
    op.create_index('idx_session_versions', 'versions', ['session_id', 'version_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_session_versions', table_name='versions')
    op.drop_index('idx_parent_version', table_name='versions')
    op.drop_index('idx_created_at', table_name='versions')
    op.drop_table('versions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
